/*
package com.lukeneedham.brailledatabase.Braille.SymbolDatabases

import com.lukeneedham.brailledatabase.Braille.BrailleCellDatabase.*
import com.lukeneedham.brailledatabase.Braille.BrailleSymbolDatabaseEntry
import com.lukeneedham.brailledatabase.Braille.BrailleSymbolDatabaseEntry.OnEntryClickType.*
import com.lukeneedham.brailledatabase.Braille.BrailleSymbolModifierType
import com.lukeneedham.brailledatabase.Braille.DictionaryCategory
import com.lukeneedham.brailledatabase.Braille.DictionaryType.*
import com.lukeneedham.brailledatabase.R

object BrailleDatabaseTamil_old : BrailleDatabase()
{

    override val dictionaryCategories =
            listOf(DictionaryCategory(R.string.symbol_uyir, 0, "அ", UYIR),
                    DictionaryCategory(R.string.symbol_uyirmei1, 1, "க", UYIRMEI1),
                    DictionaryCategory(R.string.symbol_mei, 4, "க்", MEI),
                    DictionaryCategory(R.string.symbol_uyirmei2, 7, "கா", UYIRMEI2).setTranslateToggle(true),
                    DictionaryCategory(R.string.symbol_grantha, 11, "ஷ", GRANTHA).setTranslateToggle(true),
                    DictionaryCategory(R.string.symbol_number, 13, "1", NUMBER),
                    DictionaryCategory(R.string.symbol_punctuation, 14, "?", PUNCTUATION))

    override val challengeSymbolTypes = listOf(UYIR, UYIRMEI1)

    override val canDoTranslation = true

    override val symbols = listOf(

            BrailleSymbolDatabaseEntry.LegacyConstructor("அ", UYIR, NOTHING, Cell1),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஆ", UYIR, NOTHING, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("இ", UYIR, NOTHING, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஈ", UYIR, NOTHING, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("உ", UYIR, NOTHING, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஊ", UYIR, NOTHING, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("எ", UYIR, NOTHING, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஏ", UYIR, NOTHING, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஐ", UYIR, NOTHING, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஒ", UYIR, NOTHING, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஓ", UYIR, NOTHING, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஔ", UYIR, NOTHING, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஃ", UYIR, NOTHING, Cell6),

            BrailleSymbolDatabaseEntry.LegacyConstructor("க", UYIRMEI1, NOTHING, Cell13),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ங", UYIRMEI1, NOTHING, Cell346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ச", UYIRMEI1, NOTHING, Cell14),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞ", UYIRMEI1, NOTHING, Cell25),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ட", UYIRMEI1, NOTHING, Cell23456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ண", UYIRMEI1, NOTHING, Cell3456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("த", UYIRMEI1, NOTHING, Cell2345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ந", UYIRMEI1, NOTHING, Cell1345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ப", UYIRMEI1, NOTHING, Cell1234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ம", UYIRMEI1, NOTHING, Cell134),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ய", UYIRMEI1, NOTHING, Cell13456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ர", UYIRMEI1, NOTHING, Cell1235),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ல", UYIRMEI1, NOTHING, Cell123),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வ", UYIRMEI1, NOTHING, Cell1236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழ", UYIRMEI1, NOTHING, Cell12356),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ள", UYIRMEI1, NOTHING, Cell456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ற", UYIRMEI1, NOTHING, Cell12456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ன", UYIRMEI1, NOTHING, Cell56),

            BrailleSymbolDatabaseEntry.LegacyConstructor("க்", MEI, NOTHING, Cell4, Cell13),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ங்", MEI, NOTHING, Cell4, Cell346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ச்", MEI, NOTHING, Cell4, Cell14),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞ்", MEI, NOTHING, Cell4, Cell25),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ட்", MEI, NOTHING, Cell4, Cell23456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ண்", MEI, NOTHING, Cell4, Cell3456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("த்", MEI, NOTHING, Cell4, Cell2345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ந்", MEI, NOTHING, Cell4, Cell1345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ப்", MEI, NOTHING, Cell4, Cell1234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ம்", MEI, NOTHING, Cell4, Cell134),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ய்", MEI, NOTHING, Cell4, Cell13456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ர்", MEI, NOTHING, Cell4, Cell1235),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ல்", MEI, NOTHING, Cell4, Cell123),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வ்", MEI, NOTHING, Cell4, Cell1236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழ்", MEI, NOTHING, Cell4, Cell12356),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ள்", MEI, NOTHING, Cell4, Cell456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ற்", MEI, NOTHING, Cell4, Cell12456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ன்", MEI, NOTHING, Cell4, Cell56),

            BrailleSymbolDatabaseEntry.LegacyConstructor("கா", UYIRMEI2, NOTHING, Cell13, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஙா", UYIRMEI2, NOTHING, Cell346, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("சா", UYIRMEI2, NOTHING, Cell14, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞா", UYIRMEI2, NOTHING, Cell25, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("டா", UYIRMEI2, NOTHING, Cell23456, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ணா", UYIRMEI2, NOTHING, Cell3456, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("தா", UYIRMEI2, NOTHING, Cell2345, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("நா", UYIRMEI2, NOTHING, Cell1345, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("பா", UYIRMEI2, NOTHING, Cell1234, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("மா", UYIRMEI2, NOTHING, Cell134, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("யா", UYIRMEI2, NOTHING, Cell13456, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ரா", UYIRMEI2, NOTHING, Cell1235, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("லா", UYIRMEI2, NOTHING, Cell123, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வா", UYIRMEI2, NOTHING, Cell1236, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழா", UYIRMEI2, NOTHING, Cell12356, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ளா", UYIRMEI2, NOTHING, Cell456, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("றா", UYIRMEI2, NOTHING, Cell12456, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("னா", UYIRMEI2, NOTHING, Cell56, Cell345),

            BrailleSymbolDatabaseEntry.LegacyConstructor("கி", UYIRMEI2, NOTHING, Cell13, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஙி", UYIRMEI2, NOTHING, Cell346, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("சி", UYIRMEI2, NOTHING, Cell14, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞி", UYIRMEI2, NOTHING, Cell25, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("டி", UYIRMEI2, NOTHING, Cell23456, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ணி", UYIRMEI2, NOTHING, Cell3456, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("தி", UYIRMEI2, NOTHING, Cell2345, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("நி", UYIRMEI2, NOTHING, Cell1345, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("பி", UYIRMEI2, NOTHING, Cell1234, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("மி", UYIRMEI2, NOTHING, Cell134, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("யி", UYIRMEI2, NOTHING, Cell13456, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ரி", UYIRMEI2, NOTHING, Cell1235, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("லி", UYIRMEI2, NOTHING, Cell123, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வி", UYIRMEI2, NOTHING, Cell1236, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழி", UYIRMEI2, NOTHING, Cell12356, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ளி", UYIRMEI2, NOTHING, Cell456, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("றி", UYIRMEI2, NOTHING, Cell12456, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("னி", UYIRMEI2, NOTHING, Cell56, Cell24),

            BrailleSymbolDatabaseEntry.LegacyConstructor("கீ", UYIRMEI2, NOTHING, Cell13, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஙீ", UYIRMEI2, NOTHING, Cell346, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("சீ", UYIRMEI2, NOTHING, Cell14, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞீ", UYIRMEI2, NOTHING, Cell25, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("டீ", UYIRMEI2, NOTHING, Cell23456, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ணீ", UYIRMEI2, NOTHING, Cell3456, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("தீ", UYIRMEI2, NOTHING, Cell2345, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("நீ", UYIRMEI2, NOTHING, Cell1345, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("பீ", UYIRMEI2, NOTHING, Cell1234, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("மீ", UYIRMEI2, NOTHING, Cell134, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("யீ", UYIRMEI2, NOTHING, Cell13456, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ரீ", UYIRMEI2, NOTHING, Cell1235, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("லீ", UYIRMEI2, NOTHING, Cell123, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வீ", UYIRMEI2, NOTHING, Cell1236, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழீ", UYIRMEI2, NOTHING, Cell12356, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ளீ", UYIRMEI2, NOTHING, Cell456, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("றீ", UYIRMEI2, NOTHING, Cell12456, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("னீ", UYIRMEI2, NOTHING, Cell56, Cell35),

            BrailleSymbolDatabaseEntry.LegacyConstructor("கு", UYIRMEI2, NOTHING, Cell13, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஙு", UYIRMEI2, NOTHING, Cell346, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("சு", UYIRMEI2, NOTHING, Cell14, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞு", UYIRMEI2, NOTHING, Cell25, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("டு", UYIRMEI2, NOTHING, Cell23456, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ணு", UYIRMEI2, NOTHING, Cell3456, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("து", UYIRMEI2, NOTHING, Cell2345, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("நு", UYIRMEI2, NOTHING, Cell1345, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("பு", UYIRMEI2, NOTHING, Cell1234, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("மு", UYIRMEI2, NOTHING, Cell134, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("யு", UYIRMEI2, NOTHING, Cell13456, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ரு", UYIRMEI2, NOTHING, Cell1235, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("லு", UYIRMEI2, NOTHING, Cell123, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வு", UYIRMEI2, NOTHING, Cell1236, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழு", UYIRMEI2, NOTHING, Cell12356, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ளு", UYIRMEI2, NOTHING, Cell456, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("று", UYIRMEI2, NOTHING, Cell12456, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("னு", UYIRMEI2, NOTHING, Cell56, Cell136),

            BrailleSymbolDatabaseEntry.LegacyConstructor("கூ", UYIRMEI2, NOTHING, Cell13, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஙூ", UYIRMEI2, NOTHING, Cell346, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("சூ", UYIRMEI2, NOTHING, Cell14, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞூ", UYIRMEI2, NOTHING, Cell25, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("டூ", UYIRMEI2, NOTHING, Cell23456, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ணூ", UYIRMEI2, NOTHING, Cell3456, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("தூ", UYIRMEI2, NOTHING, Cell2345, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("நூ", UYIRMEI2, NOTHING, Cell1345, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("பூ", UYIRMEI2, NOTHING, Cell1234, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("மூ", UYIRMEI2, NOTHING, Cell134, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("யூ", UYIRMEI2, NOTHING, Cell13456, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ரூ", UYIRMEI2, NOTHING, Cell1235, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("லூ", UYIRMEI2, NOTHING, Cell123, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வூ", UYIRMEI2, NOTHING, Cell1236, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழூ", UYIRMEI2, NOTHING, Cell12356, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ளூ", UYIRMEI2, NOTHING, Cell456, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("றூ", UYIRMEI2, NOTHING, Cell12456, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("னூ", UYIRMEI2, NOTHING, Cell56, Cell1256),

            BrailleSymbolDatabaseEntry.LegacyConstructor("கெ", UYIRMEI2, NOTHING, Cell13, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஙெ", UYIRMEI2, NOTHING, Cell346, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("செ", UYIRMEI2, NOTHING, Cell14, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞெ", UYIRMEI2, NOTHING, Cell25, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("டெ", UYIRMEI2, NOTHING, Cell23456, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ணெ", UYIRMEI2, NOTHING, Cell3456, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("தெ", UYIRMEI2, NOTHING, Cell2345, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("நெ", UYIRMEI2, NOTHING, Cell1345, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("பெ", UYIRMEI2, NOTHING, Cell1234, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("மெ", UYIRMEI2, NOTHING, Cell134, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("யெ", UYIRMEI2, NOTHING, Cell13456, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ரெ", UYIRMEI2, NOTHING, Cell1235, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("லெ", UYIRMEI2, NOTHING, Cell123, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வெ", UYIRMEI2, NOTHING, Cell1236, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழெ", UYIRMEI2, NOTHING, Cell12356, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ளெ", UYIRMEI2, NOTHING, Cell456, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("றெ", UYIRMEI2, NOTHING, Cell12456, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("னெ", UYIRMEI2, NOTHING, Cell56, Cell26),

            BrailleSymbolDatabaseEntry.LegacyConstructor("கே", UYIRMEI2, NOTHING, Cell13, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஙே", UYIRMEI2, NOTHING, Cell346, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("சே", UYIRMEI2, NOTHING, Cell14, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞே", UYIRMEI2, NOTHING, Cell25, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("டே", UYIRMEI2, NOTHING, Cell23456, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ணே", UYIRMEI2, NOTHING, Cell3456, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("தே", UYIRMEI2, NOTHING, Cell2345, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("நே", UYIRMEI2, NOTHING, Cell1345, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("பே", UYIRMEI2, NOTHING, Cell1234, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("மே", UYIRMEI2, NOTHING, Cell134, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("யே", UYIRMEI2, NOTHING, Cell13456, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ரே", UYIRMEI2, NOTHING, Cell1235, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("லே", UYIRMEI2, NOTHING, Cell123, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வே", UYIRMEI2, NOTHING, Cell1236, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழே", UYIRMEI2, NOTHING, Cell12356, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ளே", UYIRMEI2, NOTHING, Cell456, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("றே", UYIRMEI2, NOTHING, Cell12456, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("னே ", UYIRMEI2, NOTHING, Cell56, Cell15),

            BrailleSymbolDatabaseEntry.LegacyConstructor("கை", UYIRMEI2, NOTHING, Cell13, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஙை", UYIRMEI2, NOTHING, Cell346, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("சை", UYIRMEI2, NOTHING, Cell14, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞை", UYIRMEI2, NOTHING, Cell25, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("டை", UYIRMEI2, NOTHING, Cell23456, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ணை", UYIRMEI2, NOTHING, Cell3456, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("தை", UYIRMEI2, NOTHING, Cell2345, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("நை", UYIRMEI2, NOTHING, Cell1345, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("பை", UYIRMEI2, NOTHING, Cell1234, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("மை", UYIRMEI2, NOTHING, Cell134, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("யை", UYIRMEI2, NOTHING, Cell13456, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ரை", UYIRMEI2, NOTHING, Cell1235, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("லை", UYIRMEI2, NOTHING, Cell123, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வை", UYIRMEI2, NOTHING, Cell1236, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழை", UYIRMEI2, NOTHING, Cell12356, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ளை", UYIRMEI2, NOTHING, Cell456, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("றை", UYIRMEI2, NOTHING, Cell12456, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("னை", UYIRMEI2, NOTHING, Cell56, Cell34),

            BrailleSymbolDatabaseEntry.LegacyConstructor("கொ", UYIRMEI2, NOTHING, Cell13, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஙொ", UYIRMEI2, NOTHING, Cell346, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("சொ", UYIRMEI2, NOTHING, Cell14, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞொ", UYIRMEI2, NOTHING, Cell25, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("டொ", UYIRMEI2, NOTHING, Cell23456, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ணொ", UYIRMEI2, NOTHING, Cell3456, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("தொ", UYIRMEI2, NOTHING, Cell2345, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("நொ", UYIRMEI2, NOTHING, Cell1345, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("பொ", UYIRMEI2, NOTHING, Cell1234, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("மொ", UYIRMEI2, NOTHING, Cell134, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("யொ", UYIRMEI2, NOTHING, Cell13456, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ரொ", UYIRMEI2, NOTHING, Cell1235, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("லொ", UYIRMEI2, NOTHING, Cell123, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வொ", UYIRMEI2, NOTHING, Cell1236, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழொ", UYIRMEI2, NOTHING, Cell12356, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ளொ", UYIRMEI2, NOTHING, Cell456, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("றொ", UYIRMEI2, NOTHING, Cell12456, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("னொ", UYIRMEI2, NOTHING, Cell56, Cell1346),

            BrailleSymbolDatabaseEntry.LegacyConstructor("கோ", UYIRMEI2, NOTHING, Cell13, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஙோ", UYIRMEI2, NOTHING, Cell346, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("சோ", UYIRMEI2, NOTHING, Cell14, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞோ", UYIRMEI2, NOTHING, Cell25, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("டோ", UYIRMEI2, NOTHING, Cell23456, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ணோ", UYIRMEI2, NOTHING, Cell3456, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("தோ", UYIRMEI2, NOTHING, Cell2345, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("நோ", UYIRMEI2, NOTHING, Cell1345, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("போ", UYIRMEI2, NOTHING, Cell1234, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("மோ", UYIRMEI2, NOTHING, Cell134, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("யோ", UYIRMEI2, NOTHING, Cell13456, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ரோ", UYIRMEI2, NOTHING, Cell1235, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("லோ", UYIRMEI2, NOTHING, Cell123, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வோ", UYIRMEI2, NOTHING, Cell1236, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழோ", UYIRMEI2, NOTHING, Cell12356, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ளோ", UYIRMEI2, NOTHING, Cell456, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("றோ", UYIRMEI2, NOTHING, Cell12456, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("னோ", UYIRMEI2, NOTHING, Cell56, Cell135),

            BrailleSymbolDatabaseEntry.LegacyConstructor("கௌ", UYIRMEI2, NOTHING, Cell13, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("சௌ", UYIRMEI2, NOTHING, Cell14, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஞௌ", UYIRMEI2, NOTHING, Cell25, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("டௌ", UYIRMEI2, NOTHING, Cell23456, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ணௌ", UYIRMEI2, NOTHING, Cell3456, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("தௌ", UYIRMEI2, NOTHING, Cell2345, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("நௌ", UYIRMEI2, NOTHING, Cell1345, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("பௌ", UYIRMEI2, NOTHING, Cell1234, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("மௌ", UYIRMEI2, NOTHING, Cell134, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("யௌ", UYIRMEI2, NOTHING, Cell13456, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ரௌ", UYIRMEI2, NOTHING, Cell1235, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("லௌ", UYIRMEI2, NOTHING, Cell123, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("வௌ", UYIRMEI2, NOTHING, Cell1236, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ழௌ", UYIRMEI2, NOTHING, Cell12356, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ளௌ", UYIRMEI2, NOTHING, Cell456, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("றௌ", UYIRMEI2, NOTHING, Cell12456, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("னௌ", UYIRMEI2, NOTHING, Cell56, Cell246),

            //Sanskrit alphabets used in Tamil
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷ", GRANTHA, NOTHING, Cell12346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸ", GRANTHA, NOTHING, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹ", GRANTHA, NOTHING, Cell125),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷ", GRANTHA, NOTHING, Cell12345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜ", GRANTHA, NOTHING, Cell245),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜ்", GRANTHA, NOTHING, Cell4, Cell245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷ்", GRANTHA, NOTHING, Cell4, Cell12346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸ்", GRANTHA, NOTHING, Cell4, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹ்", GRANTHA, NOTHING, Cell4, Cell125),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷ்", GRANTHA, NOTHING, Cell4, Cell12345),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜா", GRANTHA, NOTHING, Cell245, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷா", GRANTHA, NOTHING, Cell12346, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸா", GRANTHA, NOTHING, Cell234, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹா", GRANTHA, NOTHING, Cell125, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷா", GRANTHA, NOTHING, Cell12345, Cell345),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜி", GRANTHA, NOTHING, Cell245, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷி", GRANTHA, NOTHING, Cell12346, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸி", GRANTHA, NOTHING, Cell234, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹி", GRANTHA, NOTHING, Cell125, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷி", GRANTHA, NOTHING, Cell12345, Cell24),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜீ", GRANTHA, NOTHING, Cell245, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷீ", GRANTHA, NOTHING, Cell12346, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸீ", GRANTHA, NOTHING, Cell234, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹீ", GRANTHA, NOTHING, Cell125, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷீ", GRANTHA, NOTHING, Cell12345, Cell35),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜு", GRANTHA, NOTHING, Cell245, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷு", GRANTHA, NOTHING, Cell12346, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸு", GRANTHA, NOTHING, Cell234, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹு", GRANTHA, NOTHING, Cell125, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷு", GRANTHA, NOTHING, Cell12345, Cell136),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜூ", GRANTHA, NOTHING, Cell245, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷூ", GRANTHA, NOTHING, Cell12346, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸூ", GRANTHA, NOTHING, Cell234, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹூ", GRANTHA, NOTHING, Cell125, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷூ", GRANTHA, NOTHING, Cell12345, Cell1256),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜெ", GRANTHA, NOTHING, Cell245, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷெ", GRANTHA, NOTHING, Cell12346, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸெ", GRANTHA, NOTHING, Cell234, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹெ", GRANTHA, NOTHING, Cell125, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷெ", GRANTHA, NOTHING, Cell12345, Cell26),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜே", GRANTHA, NOTHING, Cell245, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷே", GRANTHA, NOTHING, Cell12346, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸே", GRANTHA, NOTHING, Cell234, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹே", GRANTHA, NOTHING, Cell125, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷே", GRANTHA, NOTHING, Cell12345, Cell15),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜை", GRANTHA, NOTHING, Cell245, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷை", GRANTHA, NOTHING, Cell12346, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸை", GRANTHA, NOTHING, Cell234, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹை", GRANTHA, NOTHING, Cell125, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷை", GRANTHA, NOTHING, Cell12345, Cell34),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜொ", GRANTHA, NOTHING, Cell245, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷொ", GRANTHA, NOTHING, Cell12346, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸொ", GRANTHA, NOTHING, Cell234, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹொ", GRANTHA, NOTHING, Cell125, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷொ", GRANTHA, NOTHING, Cell12345, Cell1346),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜோ", GRANTHA, NOTHING, Cell245, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷோ", GRANTHA, NOTHING, Cell12346, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸோ", GRANTHA, NOTHING, Cell234, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹோ", GRANTHA, NOTHING, Cell125, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷோ", GRANTHA, NOTHING, Cell12345, Cell135),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ஜௌ", GRANTHA, NOTHING, Cell245, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஷௌ", GRANTHA, NOTHING, Cell12346, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஸௌ", GRANTHA, NOTHING, Cell234, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ஹௌ", GRANTHA, NOTHING, Cell125, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("க்ஷெள", GRANTHA, NOTHING, Cell12345, Cell246),

            //Numbers
            BrailleSymbolDatabaseEntry(listOf(BrailleDatabase.NO_STRING), descriptiveNameRes = R.string.braille_number_sign, dictionaryType = NUMBER, symbolModifierType = BrailleSymbolModifierType.INDICATOR, onEntryClickType = SHOW_INFO, cells = listOf(Cell3456), extraInfoRes = R.string.numbersExplanation, fillEntryWidth = true),
            BrailleSymbolDatabaseEntry.LegacyConstructor("1", NUMBER, NOTHING, Cell1),
            BrailleSymbolDatabaseEntry.LegacyConstructor("2", NUMBER, NOTHING, Cell12),
            BrailleSymbolDatabaseEntry.LegacyConstructor("3", NUMBER, NOTHING, Cell14),
            BrailleSymbolDatabaseEntry.LegacyConstructor("4", NUMBER, NOTHING, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("5", NUMBER, NOTHING, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("6", NUMBER, NOTHING, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("7", NUMBER, NOTHING, Cell1245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("8", NUMBER, NOTHING, Cell125),
            BrailleSymbolDatabaseEntry.LegacyConstructor("9", NUMBER, NOTHING, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("0", NUMBER, NOTHING, Cell245),
            BrailleSymbolDatabaseEntry.LegacyConstructor(".", R.string.braille_decimal_point, NUMBER, SHOW_LETTERS_REP, Cell256),
            BrailleSymbolDatabaseEntry.LegacyConstructor(",", R.string.braille_thousands_separator, NUMBER, SHOW_LETTERS_REP, Cell2),

            BrailleSymbolDatabaseEntry.LegacyConstructor(" ", INVISIBLE, NOTHING, CellEmpty),

            //Punctuation
            BrailleSymbolDatabaseEntry.LegacyConstructor(".", R.string.braille_fullstop, PUNCTUATION, SHOW_LETTERS_REP, Cell256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("?", R.string.braille_questionmark, PUNCTUATION, SHOW_LETTERS_REP, Cell26), //Different in Spanish
            BrailleSymbolDatabaseEntry.LegacyConstructor("¿", R.string.braille_questionmark_inverse, PUNCTUATION, SHOW_LETTERS_REP, Cell26), //Different in Spanish
            BrailleSymbolDatabaseEntry.LegacyConstructor("“", R.string.braille_openquote, PUNCTUATION, SHOW_LETTERS_REP, Cell236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("!", R.string.braille_exclamationmark, PUNCTUATION, SHOW_LETTERS_REP, Cell235), //Same as English
            BrailleSymbolDatabaseEntry.LegacyConstructor("¡", R.string.braille_exclamationmark_inverse, PUNCTUATION, SHOW_LETTERS_REP, Cell235), //Same as English
            BrailleSymbolDatabaseEntry.LegacyConstructor(",", R.string.braille_comma, PUNCTUATION, SHOW_LETTERS_REP, Cell2),
            BrailleSymbolDatabaseEntry.LegacyConstructor(":", R.string.braille_colon, PUNCTUATION, SHOW_LETTERS_REP, Cell25),
            BrailleSymbolDatabaseEntry.LegacyConstructor(";", R.string.braille_semicolon, PUNCTUATION, SHOW_LETTERS_REP, Cell23),
            BrailleSymbolDatabaseEntry.LegacyConstructor("'", R.string.braille_apostrophe, PUNCTUATION, SHOW_LETTERS_REP, Cell3),
            BrailleSymbolDatabaseEntry.LegacyConstructor("-", R.string.braille_hyphen, PUNCTUATION, SHOW_LETTERS_REP, Cell36),
            BrailleSymbolDatabaseEntry.LegacyConstructor("”", R.string.braille_closequote, PUNCTUATION, SHOW_LETTERS_REP, Cell356),

            BrailleSymbolDatabaseEntry(listOf(BrailleDatabase.NO_STRING), descriptiveNameRes = R.string.braille_lettersign, dictionaryType = PUNCTUATION, symbolModifierType = BrailleSymbolModifierType.INDICATOR, onEntryClickType = SHOW_INFO, cells = listOf(Cell56), extraInfoRes = R.string.lettersignExplanation),
            BrailleSymbolDatabaseEntry(listOf(BrailleDatabase.NO_STRING), descriptiveNameRes = R.string.braille_capital, dictionaryType = PUNCTUATION, symbolModifierType = BrailleSymbolModifierType.INDICATOR, onEntryClickType = SHOW_INFO, cells = listOf(Cell6), extraInfoRes = R.string.capitalsignExplanation),
            BrailleSymbolDatabaseEntry(listOf(BrailleDatabase.NO_STRING), descriptiveNameRes = R.string.braille_capitalword, dictionaryType = PUNCTUATION, symbolModifierType = BrailleSymbolModifierType.INDICATOR, onEntryClickType = SHOW_INFO, cells = listOf(Cell6, Cell6), extraInfoRes = R.string.capitalwordExplanation),

            BrailleSymbolDatabaseEntry.LegacyConstructor("*", R.string.braille_asterisk, PUNCTUATION, SHOW_LETTERS_REP, Cell5, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("(", R.string.braille_openbracket, PUNCTUATION, SHOW_LETTERS_REP, Cell5, Cell126),
            BrailleSymbolDatabaseEntry.LegacyConstructor(")", R.string.braille_closebracket, PUNCTUATION, SHOW_LETTERS_REP, Cell5, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("/", R.string.braille_slash, PUNCTUATION, SHOW_LETTERS_REP, Cell456, Cell34))
}
*/
