/*
package com.lukeneedham.brailledatabase.Braille.SymbolDatabases

import com.lukeneedham.brailledatabase.Braille.BrailleCellDatabase.*
import com.lukeneedham.brailledatabase.Braille.BrailleDatabaseDsl.cells
import com.lukeneedham.brailledatabase.Braille.BrailleDatabaseDsl.entries
import com.lukeneedham.brailledatabase.Braille.BrailleDatabaseDsl.symbol
import com.lukeneedham.brailledatabase.Braille.BrailleSymbolDatabaseEntry
import com.lukeneedham.brailledatabase.Braille.BrailleSymbolDatabaseEntry.OnEntryClickType.*
import com.lukeneedham.brailledatabase.Braille.BrailleSymbolModifierType
import com.lukeneedham.brailledatabase.Braille.BrailleSymbolUsageRule.*
import com.lukeneedham.brailledatabase.Braille.DictionaryCategory
import com.lukeneedham.brailledatabase.Braille.DictionaryType.*
import com.lukeneedham.brailledatabase.R

object BrailleDatabaseUEB_old : BrailleDatabase()
{
    override val dictionaryCategories =
            listOf(DictionaryCategory(R.string.symbol_letter, 0, "A", LETTER),
                    DictionaryCategory(R.string.symbol_number, 4, "1", NUMBER),
                    DictionaryCategory(R.string.symbol_punctuation, 6, "?", PUNCTUATION),
                    DictionaryCategory(R.string.category_contractions, 8, "~", GROUPSIGN, WORDSIGN).setTranslateToggle(true),
                    DictionaryCategory(R.string.category_advancedcontractions, 12, "~+", INITIALLETTERCONTRACTION, FINALLETTERCONTRACTION).setTranslateToggle(true),
                    DictionaryCategory(R.string.symbol_shortform, 15, "…", SHORTFORM).setTranslateToggle(true))

    override val challengeSymbolTypes = listOf(LETTER)

    override val canDoTranslation = true

    override val symbols = listOf(
            BrailleSymbolDatabaseEntry.LegacyConstructor("a", LETTER, NOTHING, Cell1),
            BrailleSymbolDatabaseEntry.LegacyConstructor("b", LETTER, NOTHING, Cell12),
            BrailleSymbolDatabaseEntry.LegacyConstructor("c", LETTER, NOTHING, Cell14),
            BrailleSymbolDatabaseEntry.LegacyConstructor("d", LETTER, NOTHING, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("e", LETTER, NOTHING, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("f", LETTER, NOTHING, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("g", LETTER, NOTHING, Cell1245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("h", LETTER, NOTHING, Cell125),
            BrailleSymbolDatabaseEntry.LegacyConstructor("i", LETTER, NOTHING, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("j", LETTER, NOTHING, Cell245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("k", LETTER, NOTHING, Cell13),
            BrailleSymbolDatabaseEntry.LegacyConstructor("l", LETTER, NOTHING, Cell123),
            BrailleSymbolDatabaseEntry.LegacyConstructor("m", LETTER, NOTHING, Cell134),
            BrailleSymbolDatabaseEntry.LegacyConstructor("n", LETTER, NOTHING, Cell1345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("o", LETTER, NOTHING, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("p", LETTER, NOTHING, Cell1234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("q", LETTER, NOTHING, Cell12345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("r", LETTER, NOTHING, Cell1235),
            BrailleSymbolDatabaseEntry.LegacyConstructor("s", LETTER, NOTHING, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("t", LETTER, NOTHING, Cell2345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("u", LETTER, NOTHING, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("v", LETTER, NOTHING, Cell1236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("w", LETTER, NOTHING, Cell2456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("x", LETTER, NOTHING, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("y", LETTER, NOTHING, Cell13456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("z", LETTER, NOTHING, Cell1356),

            BrailleSymbolDatabaseEntry(listOf(BrailleDatabase.NO_STRING), descriptiveNameRes = R.string.braille_number_sign, dictionaryType = NUMBER, symbolModifierType = BrailleSymbolModifierType.INDICATOR, onEntryClickType = SHOW_INFO, cells = listOf(Cell3456), extraInfoRes = R.string.numbersExplanation, fillEntryWidth = true),
            BrailleSymbolDatabaseEntry.LegacyConstructor("1", NUMBER, NOTHING, Cell1),
            BrailleSymbolDatabaseEntry.LegacyConstructor("2", NUMBER, NOTHING, Cell12),
            BrailleSymbolDatabaseEntry.LegacyConstructor("3", NUMBER, NOTHING, Cell14),
            BrailleSymbolDatabaseEntry.LegacyConstructor("4", NUMBER, NOTHING, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("5", NUMBER, NOTHING, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("6", NUMBER, NOTHING, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("7", NUMBER, NOTHING, Cell1245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("8", NUMBER, NOTHING, Cell125),
            BrailleSymbolDatabaseEntry.LegacyConstructor("9", NUMBER, NOTHING, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("0", NUMBER, NOTHING, Cell245),
            BrailleSymbolDatabaseEntry.LegacyConstructor(".", R.string.braille_decimal_point, NUMBER, SHOW_LETTERS_REP, Cell256),
            BrailleSymbolDatabaseEntry.LegacyConstructor(",", R.string.braille_thousands_separator, NUMBER, SHOW_LETTERS_REP, Cell2),

            BrailleSymbolDatabaseEntry.LegacyConstructor(" ", INVISIBLE, NOTHING, CellEmpty),

            BrailleSymbolDatabaseEntry.LegacyConstructor(".", R.string.braille_fullstop, PUNCTUATION, SHOW_LETTERS_REP, Cell256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("?", R.string.braille_questionmark, PUNCTUATION, SHOW_LETTERS_REP, Cell236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("!", R.string.braille_exclamationmark, PUNCTUATION, SHOW_LETTERS_REP, Cell235),
            BrailleSymbolDatabaseEntry.LegacyConstructor(",", R.string.braille_comma, PUNCTUATION, SHOW_LETTERS_REP, Cell2),
            BrailleSymbolDatabaseEntry.LegacyConstructor(":", R.string.braille_colon, PUNCTUATION, SHOW_LETTERS_REP, Cell25),
            BrailleSymbolDatabaseEntry.LegacyConstructor(";", R.string.braille_semicolon, PUNCTUATION, SHOW_LETTERS_REP, Cell23),
            BrailleSymbolDatabaseEntry.LegacyConstructor("'", R.string.braille_apostrophe, PUNCTUATION, SHOW_LETTERS_REP, Cell3),
            BrailleSymbolDatabaseEntry.LegacyConstructor("-", R.string.braille_hyphen, PUNCTUATION, SHOW_LETTERS_REP, Cell36),
            BrailleSymbolDatabaseEntry.LegacyConstructor("“", R.string.braille_openquote, PUNCTUATION, SHOW_LETTERS_REP, Cell236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("”", R.string.braille_closequote, PUNCTUATION, SHOW_LETTERS_REP, Cell356),
            BrailleSymbolDatabaseEntry(listOf(BrailleDatabase.NO_STRING), descriptiveNameRes = R.string.braille_lettersign, dictionaryType = PUNCTUATION, symbolModifierType = BrailleSymbolModifierType.INDICATOR, onEntryClickType = SHOW_INFO, cells = listOf(Cell56), extraInfoRes = R.string.lettersignExplanation),
            BrailleSymbolDatabaseEntry(listOf(BrailleDatabase.NO_STRING), descriptiveNameRes = R.string.braille_capital, dictionaryType = PUNCTUATION, symbolModifierType = BrailleSymbolModifierType.INDICATOR, onEntryClickType = SHOW_INFO, cells = listOf(Cell6), extraInfoRes = R.string.capitalsignExplanation),
            BrailleSymbolDatabaseEntry(listOf(BrailleDatabase.NO_STRING), descriptiveNameRes = R.string.braille_capitalword, dictionaryType = PUNCTUATION, symbolModifierType = BrailleSymbolModifierType.INDICATOR, onEntryClickType = SHOW_INFO, cells = listOf(Cell6, Cell6), extraInfoRes = R.string.capitalwordExplanation),
            BrailleSymbolDatabaseEntry.LegacyConstructor("*", R.string.braille_asterisk, PUNCTUATION, SHOW_LETTERS_REP, Cell5, Cell35),
            BrailleSymbolDatabaseEntry.LegacyConstructor("(", R.string.braille_openbracket, PUNCTUATION, SHOW_LETTERS_REP, Cell5, Cell126),
            BrailleSymbolDatabaseEntry.LegacyConstructor(")", R.string.braille_closebracket, PUNCTUATION, SHOW_LETTERS_REP, Cell5, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("/", R.string.braille_slash, PUNCTUATION, SHOW_LETTERS_REP, Cell456, Cell34),

            BrailleSymbolDatabaseEntry.LegacyConstructor("but", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell12),
            BrailleSymbolDatabaseEntry.LegacyConstructor("can", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell14),
            BrailleSymbolDatabaseEntry.LegacyConstructor("do", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("every", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("from", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("go", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell1245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("have", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell125),
            BrailleSymbolDatabaseEntry.LegacyConstructor("just", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("knowledge", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell13),
            BrailleSymbolDatabaseEntry.LegacyConstructor("like", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell123),
            BrailleSymbolDatabaseEntry.LegacyConstructor("more", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell134),
            BrailleSymbolDatabaseEntry.LegacyConstructor("not", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell1345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("people", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell1234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("quite", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell12345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("rather", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell1235),
            BrailleSymbolDatabaseEntry.LegacyConstructor("so", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("that", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell2345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("us", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("very", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell1236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("will", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell2456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("it", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell1346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("you", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell13456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("as", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell1356),

            BrailleSymbolDatabaseEntry.LegacyConstructor("gg", SURROUNDED, GROUPSIGN, SHOW_USAGE_RULE, Cell2356),
            BrailleSymbolDatabaseEntry.LegacyConstructor("were", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell2356),
            BrailleSymbolDatabaseEntry.LegacyConstructor("st", GROUPSIGN, SHOW_USAGE_RULE, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("still", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ch", GROUPSIGN, SHOW_USAGE_RULE, Cell16),
            BrailleSymbolDatabaseEntry.LegacyConstructor("child", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell16),
            BrailleSymbolDatabaseEntry.LegacyConstructor("gh", GROUPSIGN, SHOW_USAGE_RULE, Cell126),
            BrailleSymbolDatabaseEntry.LegacyConstructor("sh", GROUPSIGN, SHOW_USAGE_RULE, Cell146),
            BrailleSymbolDatabaseEntry.LegacyConstructor("shall", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell146),
            BrailleSymbolDatabaseEntry.LegacyConstructor("th", GROUPSIGN, SHOW_USAGE_RULE, Cell1456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("this", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell1456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("wh", GROUPSIGN, SHOW_USAGE_RULE, Cell156),
            BrailleSymbolDatabaseEntry.LegacyConstructor("which", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell156),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ed", GROUPSIGN, SHOW_USAGE_RULE, Cell1246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("er", GROUPSIGN, SHOW_USAGE_RULE, Cell12456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ou", GROUPSIGN, SHOW_USAGE_RULE, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("out", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ow", GROUPSIGN, SHOW_USAGE_RULE, Cell246),
            BrailleSymbolDatabaseEntry.LegacyConstructor("en", GROUPSIGN, SHOW_USAGE_RULE, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("enough", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell26),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ing", NOT_AT_START, GROUPSIGN, SHOW_USAGE_RULE, Cell346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ar", GROUPSIGN, SHOW_USAGE_RULE, Cell345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("in", GROUPSIGN, SHOW_USAGE_RULE, Cell35),

            BrailleSymbolDatabaseEntry.LegacyConstructor("and", GROUPSIGN, SHOW_USAGE_RULE, Cell12346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("for", GROUPSIGN, SHOW_USAGE_RULE, Cell123456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("of", GROUPSIGN, SHOW_USAGE_RULE, Cell12356),
            BrailleSymbolDatabaseEntry.LegacyConstructor("the", GROUPSIGN, SHOW_USAGE_RULE, Cell2346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("with", GROUPSIGN, SHOW_USAGE_RULE, Cell23456),

            BrailleSymbolDatabaseEntry.LegacyConstructor("dis", FIRST_SYLLABLE, GROUPSIGN, SHOW_USAGE_RULE, Cell256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("his", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ff", SURROUNDED, GROUPSIGN, SHOW_USAGE_RULE, Cell235),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ea", SURROUNDED, GROUPSIGN, SHOW_USAGE_RULE, Cell2),
            BrailleSymbolDatabaseEntry.LegacyConstructor("con", FIRST_SYLLABLE, GROUPSIGN, SHOW_USAGE_RULE, Cell25),
            BrailleSymbolDatabaseEntry.LegacyConstructor("cc", SURROUNDED, GROUPSIGN, SHOW_USAGE_RULE, Cell25),
            BrailleSymbolDatabaseEntry.LegacyConstructor("bb", SURROUNDED, GROUPSIGN, SHOW_USAGE_RULE, Cell23),
            BrailleSymbolDatabaseEntry.LegacyConstructor("be", FIRST_SYLLABLE, GROUPSIGN, SHOW_USAGE_RULE, Cell23),
            BrailleSymbolDatabaseEntry.LegacyConstructor("was", STANDALONE, WORDSIGN, SHOW_USAGE_RULE, Cell356),

            BrailleSymbolDatabaseEntry.LegacyConstructor("upon", ORIGINAL_MEANING_RETAINED, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell45, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("these", ORIGINAL_MEANING_RETAINED, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell45, Cell2346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("those", ORIGINAL_MEANING_RETAINED, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell45, Cell1456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("whose", ORIGINAL_MEANING_RETAINED, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell45, Cell156),
            BrailleSymbolDatabaseEntry.LegacyConstructor("word", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell45, Cell2456),

            BrailleSymbolDatabaseEntry.LegacyConstructor("cannot", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell456, Cell14),
            BrailleSymbolDatabaseEntry.LegacyConstructor("had", SHORT_A, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell456, Cell125),
            BrailleSymbolDatabaseEntry.LegacyConstructor("many", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell456, Cell134),
            BrailleSymbolDatabaseEntry.LegacyConstructor("spirit", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell456, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("their", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell456, Cell2346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("world", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell456, Cell2456),

            BrailleSymbolDatabaseEntry.LegacyConstructor("day", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ever", STRESS_ON_FIRST_E_AND_NOT_AFTER_I_OR_E, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("father", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("here", ONE_SYLLABLE, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell125),
            BrailleSymbolDatabaseEntry.LegacyConstructor("know", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell13),
            BrailleSymbolDatabaseEntry.LegacyConstructor("lord", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell123),
            BrailleSymbolDatabaseEntry.LegacyConstructor("mother", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell134),
            BrailleSymbolDatabaseEntry.LegacyConstructor("name", ONE_SYLLABLE, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell1345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("one", ONE_SYLLABLE_OR_END_WITH_ONEY_BUT_NEVER_AFTER_O, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell135),
            BrailleSymbolDatabaseEntry.LegacyConstructor("part", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell1234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("question", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell12345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("right", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell1235),
            BrailleSymbolDatabaseEntry.LegacyConstructor("some", ONE_SYLLABLE, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("time", ORIGINAL_PRONOUNCIATION_RETAINED, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell2345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("under", NOT_AFTER_A_OR_O_AND_UN_NOT_A_PREFIX, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell136),
            BrailleSymbolDatabaseEntry.LegacyConstructor("young", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell13456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("there", ORIGINAL_MEANING_RETAINED, INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell2346),
            BrailleSymbolDatabaseEntry.LegacyConstructor("character", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell16),
            BrailleSymbolDatabaseEntry.LegacyConstructor("through", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell1456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("where", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell156),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ought", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell1256),
            BrailleSymbolDatabaseEntry.LegacyConstructor("work", INITIALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell5, Cell2456),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ound", NOT_AT_START, FINALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell46, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ance", NOT_AT_START, FINALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell46, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("sion", NOT_AT_START, FINALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell46, Cell1345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("less", NOT_AT_START, FINALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell46, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ount", NOT_AT_START, FINALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell46, Cell2345),

            BrailleSymbolDatabaseEntry.LegacyConstructor("ence", NOT_AT_START, FINALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell56, Cell15),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ong", NOT_AT_START, FINALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell56, Cell1245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ful", NOT_AT_START, FINALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell56, Cell123),
            BrailleSymbolDatabaseEntry.LegacyConstructor("tion", NOT_AT_START, FINALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell56, Cell1345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ness", NOT_AT_START, FINALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell56, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ment", NOT_AT_START, FINALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell56, Cell2345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ity", NOT_AT_START, FINALLETTERCONTRACTION, SHOW_USAGE_RULE, Cell56, Cell13456),

            BrailleSymbolDatabaseEntry.LegacyConstructor("about", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell12),
            BrailleSymbolDatabaseEntry.LegacyConstructor("above", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell12, Cell1236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("according", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell14),
            BrailleSymbolDatabaseEntry.LegacyConstructor("across", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell14, Cell1235),
            BrailleSymbolDatabaseEntry.LegacyConstructor("after", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("afternoon", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell124, Cell1345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("afterward", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell124, Cell2456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("again", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell1245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("against", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell1245, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("also", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell123),
            BrailleSymbolDatabaseEntry.LegacyConstructor("almost", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell123, Cell134),
            BrailleSymbolDatabaseEntry.LegacyConstructor("already", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell123, Cell1235),
            BrailleSymbolDatabaseEntry.LegacyConstructor("altogether", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell123, Cell2345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("although", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell123, Cell1456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("always", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1, Cell123, Cell2456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("blind", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell12, Cell123),
            BrailleSymbolDatabaseEntry.LegacyConstructor("braille", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell12, Cell1235, Cell123),
            BrailleSymbolDatabaseEntry.LegacyConstructor("could", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell14, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("declare", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell145, Cell14, Cell123),
            BrailleSymbolDatabaseEntry.LegacyConstructor("declaring", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell145, Cell14, Cell123, Cell1245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("deceive", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell145, Cell14, Cell1236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("deceiving", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell145, Cell14, Cell1236, Cell1245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("either", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell15, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("friend", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell124, Cell1235),
            BrailleSymbolDatabaseEntry.LegacyConstructor("first", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell124, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("good", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1245, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("great", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1245, Cell1235, Cell2345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("him", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell125, Cell134),
            BrailleSymbolDatabaseEntry.LegacyConstructor("himself", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell125, Cell134, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("herself", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell125, Cell12456, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("immediate", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell24, Cell134, Cell134),
            BrailleSymbolDatabaseEntry.LegacyConstructor("little", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell123, Cell123),
            BrailleSymbolDatabaseEntry.LegacyConstructor("letter", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell123, Cell1235),
            BrailleSymbolDatabaseEntry.LegacyConstructor("myself", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell134, Cell13456, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("much", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell134, Cell16),
            BrailleSymbolDatabaseEntry.LegacyConstructor("must", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell134, Cell34),
            BrailleSymbolDatabaseEntry.LegacyConstructor("necessary", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1345, Cell15, Cell14),
            BrailleSymbolDatabaseEntry.LegacyConstructor("neither", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1345, Cell15, Cell24),
            BrailleSymbolDatabaseEntry.LegacyConstructor("paid", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1234, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("perceive", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1234, Cell12456, Cell14, Cell1236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("perceiving", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1234, Cell12456, Cell14, Cell1236, Cell1245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("perhaps", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1234, Cell12456, Cell125),
            BrailleSymbolDatabaseEntry.LegacyConstructor("quick", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell12345, Cell13),
            BrailleSymbolDatabaseEntry.LegacyConstructor("receive", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1235, Cell14, Cell1236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("receiving", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1235, Cell14, Cell1236, Cell1245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("rejoice", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1235, Cell245, Cell14),
            BrailleSymbolDatabaseEntry.LegacyConstructor("rejoicing", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1235, Cell245, Cell14, Cell1245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("said", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell234, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("such", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell234, Cell16),
            BrailleSymbolDatabaseEntry.LegacyConstructor("today", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell2345, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("together", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell2345, Cell1245, Cell1235),
            BrailleSymbolDatabaseEntry.LegacyConstructor("tomorrow", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell2345, Cell134),
            BrailleSymbolDatabaseEntry.LegacyConstructor("tonight", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell2345, Cell1345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("itself", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1346, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("its", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1346, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("your", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell13456, Cell1235),
            BrailleSymbolDatabaseEntry.LegacyConstructor("yourself", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell13456, Cell1235, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("yourselves", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell13456, Cell1235, Cell1236, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("themselves", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell2346, Cell134, Cell1236, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("children", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell16, Cell1345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("should", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell146, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("thyself", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1456, Cell13456, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("ourselves", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell1256, Cell1235, Cell1236, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("would", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell2456, Cell145),
            BrailleSymbolDatabaseEntry.LegacyConstructor("because", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell23, Cell14),
            BrailleSymbolDatabaseEntry.LegacyConstructor("before", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell23, Cell124),
            BrailleSymbolDatabaseEntry.LegacyConstructor("behind", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell23, Cell125),
            BrailleSymbolDatabaseEntry.LegacyConstructor("below", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell23, Cell123),
            BrailleSymbolDatabaseEntry.LegacyConstructor("beneath", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell23, Cell1345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("beside", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell23, Cell234),
            BrailleSymbolDatabaseEntry.LegacyConstructor("between", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell23, Cell2345),
            BrailleSymbolDatabaseEntry.LegacyConstructor("beyond", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell23, Cell13456),
            BrailleSymbolDatabaseEntry.LegacyConstructor("conceive", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell25, Cell14, Cell1236),
            BrailleSymbolDatabaseEntry.LegacyConstructor("conceiving", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell25, Cell14, Cell1236, Cell1245),
            BrailleSymbolDatabaseEntry.LegacyConstructor("oneself", STANDALONE, SHORTFORM, SHOW_USAGE_RULE, Cell5, Cell135, Cell124))
}
*/
